---
- name: "configure | logrotate | deploy logrotate configuration"
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - { src: logrotate/nginx_general.j2, dest: /etc/logrotate.d/nginx }
    - { src: logrotate/nginx_vhost.j2, dest: /etc/logrotate.d/nginx-vhost }
