---
- name: "configure | ssl_config | deploy ssl configurations"
  ansible.builtin.template:
    dest: '/etc/nginx/{{ item.dest }}'
    src: '{{ item.src }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: yes
  loop:
    - { src: 'nginx/configs/ssl/ssl-ciphers.conf.j2', dest: 'conf.d/ssl/configs/ssl-ciphers.conf' }
    - { src: 'nginx/configs/ssl/ssl-hardening.conf.j2', dest: 'conf.d/ssl/configs/ssl-hardening.conf' }
