---
- name: "import RHEL tasks"
  ansible.builtin.import_tasks: rhel/main.yml
  when: (ansible_distribution == 'Rocky' and ansible_distribution_major_version|int >= 8) or
        (ansible_distribution == 'RedHat' and ansible_distribution_major_version|int >= 8)

- name: "import Debian tasks"
  ansible.builtin.import_tasks: debian/main.yml
  when: (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 10) or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 17)
