---
- name: "prerequisites | debian | install required packages"
  ansible.builtin.apt:
    name: "{{ debian['packages'] }}"
    dpkg_options: "{{ debian['dpkg_options'] }}"
    state: present
    force_apt_get: yes
    install_recommends: no
