---
- name: "configure | base_config | clean_base_file | remove default useless files"
  file:
    path: '/etc/nginx/{{ item }}'
    state: absent
  with_items:
    - fastcgi.conf
    - fastcgi.conf.default
    - fastcgi_params
    - fastcgi_params.default
    - koi-utf
    - koi-win
    - mime.types.default
    - nginx.conf.default
    - scgi_params
    - scgi_params.default
    - uwsgi_params
    - uwsgi_params.default
    - win-utf
    - default.d
