---
- name: "configure | stub_status | deploy stub_status configuration"
  ansible.builtin.template:
    dest: /etc/nginx/conf.d/stub_status.conf
    src: nginx/configs/stub_status.conf.j2
    group: 'root'
    mode: '0644'
    owner: 'root'
    backup: yes
  notify: restart nginx
